### ISSUE TITLE
invalid memory address or nil pointer

### ISSUE THREAD

**Issue by Madhu1512** [codesuki/ecs-gen#14] opened 2017-04-03 14:18 UTC
nginx-ecs-proxy container continuously getting killed with the following error.

2017/04/03 13:51:05 updating config
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x403a3d]

goroutine 1 [running]:
panic(0x97b5c0, 0xc420010030)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.(*scanner).makeIDAddressMap(0xc420155d80, 0x6, 0xa362ad, 0x6)
	/go/src/github.com/codesuki/ecs-gen/scanner.go:58 +0x17d
main.(*scanner).scan(0xc420155d80, 0xc420155dc0, 0x412cce, 0xc4200201f8, 0x8, 0x8)
	/go/src/github.com/codesuki/ecs-gen/scanner.go:36 +0x171
main.updateAndWrite(0xc4200201e0, 0xc4200201f8)
	/go/src/github.com/codesuki/ecs-gen/main.go:95 +0x99
main.execute(0xc4200201e0, 0xc4200201f8)
	/go/src/github.com/codesuki/ecs-gen/main.go:80 +0x55
main.main()
	/go/src/github.com/codesuki/ecs-gen/main.go:73 +0x1d1

Not sure what's causing it. But It was working fine when we first deployed. During Off Hours, We put our autoscaling group to suspend state and resume during the work hours. After resuming the autoscaling group from a suspended state, we continuously see this issue.

**Comment by codesuki** [comment] 2017-04-18 04:41
Thanks for the report! Sorry for the late response, I was on vacation.
I'll have a look. Did you investigate anything more since then?

**Comment by lucaschain** [comment] 2017-05-17 18:02
I have it too from time to time

**Comment by lucaschain** [comment] 2017-05-17 18:44
The problem is: 
When you have a terminated instance on your ECS cluster, ecs-gen tried to get its private IP, but terminated instances does not have one.
For the solution, I created this pull request that checks if the instance has a private IP address before using it.

**Comment by codesuki** [comment] 2017-06-05 03:17
Should be fixed by #16

**Closed as completed by codesuki** 2017-06-05 03:17 UTC

**Comment by Madhu1512** [comment] 2017-06-05 23:02
Can we get a new release of ecs-gen with this fix included?

**Comment by codesuki** [comment] 2017-06-06 01:54
Yes! Very soon.
